### ISSUE TITLE
i have periodically error in asyncio.py

### ISSUE THREAD

**Issue by ofilin86** [nathan-hoad/python-icap#2]
Error:

```
Error while processing REQMOD request
Traceback (most recent call last):
  File "/opt/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/opt/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/opt/python-icap/icap/asyncio.py", line 223, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
```

Fix in file asyncio.py, from line 219:

```
        if l:
            http.headers.replace('Content-Length', str(l))
        else:
            try:
                http.headers.pop('Content-Length', None)
            except KeyError:
                pass

        return response
```

**Comment by nathan-hoad** [comment]
Hello, from this it looks like you're using threads in your code, because that's the only way that collections.OrderedDict.pop will raise a KeyError when given a default. You should either stop using threads or you should ensure they're finished doing their work before letting your request handler finish, otherwise unknown behaviour (like the above) will occur.

**Comment by ofilin86** [comment]
Hello, I'm using your example and getting error
```
from icap import DomainCriteria, handler, run

@handler(DomainCriteria('*google.*'))
def reqmod(request):
    query = request.request_line.query
    if 'q' in query:
        request.request_line.query['q'][0] += ' without my pants'

if __name__ == '__main__':
    run(host='127.0.0.1', port=1334)
```

Error:
```

X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
Error while processing REQMOD request
Traceback (most recent call last):
  File "/usr/local/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 222, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
Error while processing REQMOD request
Traceback (most recent call last):
  File "/usr/local/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 222, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
Error while processing REQMOD request
Traceback (most recent call last):
  File "/usr/local/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 222, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
Error while processing REQMOD request
Traceback (most recent call last):
  File "/usr/local/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 222, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
X-Session-ID header not available, using UUID
Error while processing REQMOD request
Traceback (most recent call last):
  File "/usr/local/python-icap/icap/asyncio.py", line 119, in handle_request
    response = yield from self.dispatch_request(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 188, in dispatch_request
    response = yield from self.handle_mod(request, handler, raw)
  File "/usr/local/python-icap/icap/asyncio.py", line 222, in handle_mod
    http.headers.pop('Content-Length', None)
  File "/usr/lib/python3.4/collections/__init__.py", line 180, in pop
    del self[key]
  File "/usr/lib/python3.4/collections/__init__.py", line 76, in __delitem__
    dict_delitem(self, key)
KeyError: 'Content-Length'
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID
X-Session-ID header not available, using UUID


```
